
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(knitr)
library(stargazer)
library(reshape2)
library(cowplot)
library(akima)
```

# I. Dynamic Programming to find Timestep = 1

```{r}

# Find Patch A Sole Owner Scenario (e_a*)

df_all = data.frame()
V_next = matrix(0, size_x_a, size_x_b)
V = matrix(0, size_x_a, size_x_b)

for(t in T:1) {
  for(i in 1:size_x_a) {
    x_a = x_a_grid[i]
    for(j in 1:size_x_b) {
      x_b = x_b_grid[j]
      guess = x_a/2
      low = 0 #lower bound on escapement in A
      high = x_a #upper bound on escapement in A
      Thing = optim(par=guess, fn=payoff, lower=low, upper=high, x_a=x_a, x_b=x_b, V=V, method='L-BFGS-B')
      e_a_star = Thing$par
      V_star = -Thing$value
      V_next[i,j] = V_star
      df_now = data.frame(time=t, x_a=x_a, x_b=x_b, e_a_star=e_a_star, V_star=V_star)
      df_all = rbind(df_all, df_now)
    }
  }
  V = V_next
}

df_inf = df_all %>% filter(time==1) %>% select(-time, -V_star) %>% add_column(timestep=1) %>% 
  filter(x_a == 25.1464380189645) %>% filter(x_b == 11.6291041955)

```

#II. Sole Owner Patch A (Reserve Scenario)

```{r}

# Sole Owner Scenario

results_so <- tibble(
  timestep = integer(), 
  x_a_init = numeric(),
  x_a = numeric(), 
  h_a = numeric(), 
  e_a_star = numeric(), 
  x_b_init = numeric(),
  x_b = numeric(), 
  h_b = numeric(), 
  e_b_star = numeric(),
  NPV_ea_star = numeric(),
  NPV_eb_star = numeric()
)

# Initialize NPV variables
NPV_ea_star <- 0
NPV_eb_star <- 0

# Storing initial values
x_a_init <- df_inf$x_a
x_b_init <- df_inf$x_b

x_a <- df_inf$x_a
x_b <- df_inf$x_b

df_row <- df_inf 

for(t in 1:timesteps) {
  
  e_a_star <- df_row$e_a_star
  e_b_star <- df_row$x_b
  h_a_val = h_a(x_a, e_a_star)
  h_b_val = h_b(x_b, 0)
  x_a_new = next_x_a(e_a_star, e_b_star) - mu_a*M_aa*e_a_star - mu_b*M_ba*e_b_star + mu_a*M_aa*e_a_star + mu_b*M_ba*e_b_star
  x_b_new = next_x_b(e_a_star, e_b_star) - mu_b*M_bb*e_b_star - mu_a*M_ab*e_a_star + mu_b*M_bb*e_b_star + mu_a*M_ab*e_a_star 
  V_a_star = b_a(p_a, c_a) * (x_a - e_a_star) * delta^(t-1)
  V_b_star = b_b(p_b, c_b) * (x_b - e_b_star) * delta^(t-1)
  NPV_ea_star <- NPV_ea_star + V_a_star
  NPV_eb_star <- NPV_eb_star + V_b_star
  results_so <- results_so %>%
    add_row(
      timestep = t,
      x_a_init = x_a_init,
      x_a = x_a,
      h_a = h_a_val,
      x_b_init = x_b_init,
      x_b = x_b,
      h_b = h_b_val,
      e_a_star = e_a_star,
      e_b_star = e_b_star,
      NPV_ea_star = NPV_ea_star,
      NPV_eb_star = NPV_eb_star
    )
  x_a <- x_a_new
  x_b <- x_b_new
}

print(results_so)

df_results_so = results_so %>% filter(timestep == 100) %>% select(-timestep)


```